aws:
  region: us-east-2

s3:
  log_bucket: cloudtrail-logs-company123
  log_prefix: AWSLogs/   
  alert_bucket: anomaly-alerts-company123
  alert_prefix: alerts

dynamodb:
  baseline_table: BaselineData
  processed_table: ProcessedS3Logs
  processed_key_ttl_days: 1

  promotion:
    min_count: 3
    max_age_days: 7

polling:
  interval_seconds: 30

cleanup:
  candidate_max_age_days: 14
  baseline_max_age_days: 60
  delete_missing_users: true

sqs:
  detection_queue_url: https://sqs.us-east-2.amazonaws.com/732406385148/detection-queue

detection:
  burn_in_days: 0

  suppressed_actor_types:
    - service
    - anonymous

defaults:
  allowed_hours_by_region:
    us-east-1: ["08", "09", "10", "11", "12", "13", "14", "15", "16", "17"]
    us-west-1: ["10", "11", "12", "13", "14", "15", "16", "17", "18"]
    us-west-2: ["10", "11", "12", "13", "14", "15", "16", "17", "18"]
    us-east-2: ["08", "09", "10", "11", "12", "13", "14", "15", "16"]

users:
  Cardell:
    allowed_hours_utc: ["06", "07", "08", "09", "10", "11", "12", "18", "19"]
