aws:
  region: us-east-2

s3:
  log_bucket: cloudtrail-logs-company123        # from var.cloudtrail_bucket_name
  log_prefix: AWSLogs/
  alert_bucket: anomaly-alerts-company123       # from var.alert_bucket_name
  alert_prefix: alerts/

dynamodb:
  baseline_table: BaselineData                  # from var.baseline_table_name
  promotion:
    min_count: 3
    max_age_days: 7
  processed_table: ProcessedS3Logs              # optional, if used
  processed_key_ttl_days: 1

polling:
  interval_seconds: 30

cleanup:
  candidate_max_age_days: 14
  baseline_max_age_days: 60
  delete_missing_users: true

sqs:
  baseline_queue_url: https://sqs.us-east-2.amazonaws.com/732406385148/baseline-queue

