aws:
  region: us-east-2

s3:
  log_bucket: cloudtrail-logs-84917      # ← matches your S3 log bucket with suffix
  log_prefix: AWSLogs/
  alert_bucket: anomaly-alerts-84917     # ← your detection alert bucket with suffix
  alert_prefix: alerts/

dynamodb:
  baseline_table: BaselineData           # ← table created in Terraform
  processed_table: ProcessedS3Logs       # ← optional, define if you use deduplication
  processed_key_ttl_days: 1

  promotion:
    min_count: 3
    max_age_days: 7

polling:
  interval_seconds: 30

cleanup:
  candidate_max_age_days: 14
  baseline_max_age_days: 60
  delete_missing_users: true

sqs:
  detection_queue_url: https://sqs.us-east-2.amazonaws.com/732406385148/detection-queue

